CREATE TYPE "DiscountType" AS ENUM ('FIXED_AMOUNT', 'PERCENTAGE');

ALTER TABLE "LaundryOrder"
ADD COLUMN "discountType" "DiscountType" NOT NULL DEFAULT 'FIXED_AMOUNT',
ADD COLUMN "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
